
# -*- coding: utf-8 -*-
"""code_generation_positive.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1h89MWq5iBIgii_DPO3ML46wi_8ASzA49
"""

# Python3 code to demonstrate
# the random generation of string id's

import random
import string

# defining function for random
# string id with parameter
def ran_gen(size, chars=string.ascii_uppercase + string.digits):
	return ''.join(random.choice(chars) for x in range(size))

# function call for random string
# generation with size 8 and string
def code():
    a= (ran_gen(6, "13456789AXCNMLERTSEKIASDDYYZZWJHGFREWSDFVBMJ5679SQJH"))
    b= "COV19"
    d="20P"
    c= b+a+d
    return c
