# -*- coding: utf-8 -*-
"""oxymeter

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JHUHrbeq-BEnvOZ3aUIictCAtjCqXi-j
"""

def oxymeter(spo2):
  

  if(spo2<=95):
    return(1)
  else:
    return(0)
