# -*- coding: utf-8 -*-
"""spiro.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mS7A58gZb5P7s74Mxn975HfBRPivW8Sk
"""

def spiro(fev,fvc):
   x = (fev/fvc)
  
   y = x*100
   if(y>= 70):
     return(0)
   elif (y>=60) & (y<=69):
     return(1)
   elif (y>=50) & (y<=59):
     return(2)
   else :
     return(3)


