# -*- coding: utf-8 -*-
"""temp_check.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14IokOSj7cxUTHZJL5iyId-6830ER5gNW
"""

def temp_check(temp):

  if (temp>98.00):
        return 1
  else:
        return 0

#temp_check()
