# -*- coding: utf-8 -*-
"""temp_check.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HNagTswEY0qcoG82QScAXL45YHqw6zHM
"""

def temp_check():
  temp = float(input("checking for temperature:"))

  if (temp>98.00):
        return 1
  else:
        return 0

temp_check()